test/helpers: Use a proper cast for `(struct sockaddr *)` argument
Sometimes the compiler accepts (struct sockaddr_in *) to be passed in
to (struct sockaddr *) without a cast. But not all compilers agree with
that. Building with clang 13.0.1 yields the following error:

  error: incompatible pointer types passing 'struct sockaddr_in *' to \
  parameter of type 'struct sockaddr *' [-Werror,-Wincompatible-pointer-types]

Explicitly cast the pointer to (struct sockaddr *) to avoid this error.

Cc: kernel-team@fb.com
Cc: Dylan Yudaken <dylany@fb.com>
Fixes: 8e3d3518ade9d7de94c9770a6db13e8d8f4681b5 ("add t_create_socket_pair")
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>
Link: https://lore.kernel.org/r/20220703063755.189175-1-ammar.faizi@intel.com
Signed-off-by: Jens Axboe <axboe@kernel.dk>