fix missing '#include <sys/stat.h>' in 'src/include/liburing.h
make failed on musl libc system when entering test subdir with this:
-----
make[1]: Entering directory '/work/devel/liburing/test'
     CC poll
In file included from poll.c:12:
/usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
    1 | #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
      |  ^~~~~~~
In file included from poll.c:15:
../src/include/liburing.h:339:35: error: unknown type name 'mode_t'
  339 |      const char *path, int flags, mode_t mode)
      |                                   ^~~~~~
make[1]: *** [Makefile:39: poll] Error 1
make[1]: Leaving directory '/work/devel/liburing/test'
make: *** [Makefile:13: all] Error 2
-----

adding #include <sys/stat.h> to src/include/liburing.h fixes build

Signed-off-by: Milan P. Stanić <mps@arvanta.net>
Signed-off-by: Jens Axboe <axboe@kernel.dk>