liburing.h: define GNU_SOURCE for cpu_set_t
On musl, cpu_set_t is only exposed if GNU_SOURCE is defined. While in
the liburing build system, this is set (5ebfd161d7db5b97b98da4b4c1f492e5f5a2e731),
it can't be guaranteed that folks including the header externally will set
that macro.

Noticed while investigating a build failure for glusterfs on a musl
system:
```
configure:17701: checking for liburing.h
configure:17701: x86_64-gentoo-linux-musl-gcc -c -pipe -march=native -fno-diagnostics-color -O2  conftest.c >&5
In file included from conftest.c:105:
/usr/include/liburing.h:162:39: error: unknown type name 'cpu_set_t'
  162 |                                 const cpu_set_t *mask);
      |                                       ^~~~~~~~~
configure:17701: $? = 1
```

Just like _XOPEN_SOURCE, set if needed.

Bug: https://bugs.gentoo.org/829293
Bug: https://github.com/axboe/liburing/issues/422
See: 5ebfd161d7db5b97b98da4b4c1f492e5f5a2e731
Signed-off-by: Sam James <sam@gentoo.org>