test/skip-cqe: use correct index for write side of pipe
clang correctly complains about using out-of-array:

skip-cqe.c:19:27: error: array index 2 is past the end of the array (which contains 2 elements) [-Werror,-Warray-bounds]

        io_uring_prep_write(sqe, fds[2], NULL, 100, 0);
	                         ^   ~

Fixes: 4d9830f9cfc5 ("tests: add tests for IOSQE_CQE_SKIP_SUCCESS")
Signed-off-by: Jens Axboe <axboe@kernel.dk>